### ISSUE TITLE
Concatenate roles CKAN

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/ckan#13]
I'm hoping it would be possible to concatenate the multiple roles assigned to a contact under the same 'item', eg:

Individual Name: Brian Hunt
Organisation Name / Affiliation: University of British Columbia
Contact Info Email: b.hunt@oceans.ubc.ca
Role: Principal Investigator, Author, Owner, Custodian

Instead of this being 4 separate contact items. 

Thanks!

**Comment by timvdstap** [comment]
Hi @fostermh - would you happen to have an update on the status of this item?

**Comment by fostermh** [comment]
yep, haven't got to it but I will.

**Comment by Br-Johnson** [comment]
It looks like this has been fixed in the Hakai and CIOOS catalogues but not in the IYS catalogue yet.

**Comment by Br-Johnson** [comment]
Despite the recent update, this is still an issue

**Comment by fostermh** [comment]
Jan 14th update may have fixed this, please confirm.

**Comment by Br-Johnson** [comment]
It looks to me like this is fixed now. 

@timvdstap look OK to you? I see we still have separate sections for Point of Contact, Responsible Party and now also 'Distributor', though we have another issue open for that at https://github.com/HakaiInstitute/ckan/issues/12

Atleast now the names aren't duplicated for each role within those sections.

![image](https://user-images.githubusercontent.com/26495640/150181245-968693c6-50cd-496c-8406-4263112f16bf.png)

**Comment by timvdstap** [comment]
Yes, looks good to me, happy to see that the roles are concatenated, though indeed interesting to see "Distributor" mentioned as well.
