### ISSUE TITLE
Protocol: enter multiple resource contact affiliations?

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/ckan#15]
Perhaps not so much an issue as it is a question: Is there a protocol on how to enter/include organizational information for resource contacts that have multiple affiliations?

**Comment by Br-Johnson** [comment]
@timvdstap Probably just use their primary/highest level affiliation? LIke for Brian Hunt for example I would just say UBC

**Comment by timvdstap** [comment]
That works for me, so if that's how other people are including that information then I'll also do that! 👍
