### ISSUE TITLE
Discrepancy: Preliminary citation vs. citation in published metadata record

### ISSUE THREAD

**Issue by timvdstap** [HakaiInstitute/ckan#17]
It seems that in metadata records in IYS CKAN, the NPAFC is included in the citation, see e.g. [here](https://iys.hakai.org/dataset/ca-cioos_fdba20a9-0e91-4e37-bf5f-086b08d56209). In the metadata intake form, the NPAFC is listed as 'Publisher' and not included in the preliminary citation (which is preferred for us). Any reason why there's a discrepancy in what's shown in the preliminary citation, and in the CKAN records?

**Comment by Br-Johnson** [comment]
I think the publisher should have it's own section like how DataCite formats citations:

Creator (PublicationYear). Title. Publisher. Identifier

https://datacite.org/cite-your-data.html

**Comment by Br-Johnson** [comment]
This is still an issue

**Comment by fostermh** [comment]
Jan 14th update may have fixed this, please confirm.

**Comment by Br-Johnson** [comment]
Looks good now! Thanks @fostermh.

**Comment by Br-Johnson** [comment]
NPAFC is removed from IYS records, however, now I see that in the Hakai catalogue people with the role 'Contributor' are being included in the recommended citation in CKAN. That's different than in the metadata intake form preview @fostermh @n-a-t-e

**Comment by timvdstap** [comment]
I'm not sure this is fixed, because I see North Pacific Anadromous Fish Commission still included in the citation, though now in a separate section (whereas I believe it should be omitted from the citation all together). 

![image](https://user-images.githubusercontent.com/62965116/150189862-6204974c-3efb-4c83-9db1-47ea96ab85c2.png)

**Comment by Br-Johnson** [comment]
NPAFC is included in the citation because they are listed as the Publisher in the metadata record. Including the publisher in the citation is actually the preferred standard from DataCite. From the [DataCite metadata schema](https://doi.org/10.14454/3w3z-sa82):

"The following is the preferred format for rendering a DataCite citation for human readers using the mandatory properties of the schema: 

Creator (PublicationYear): Title. Publisher. (resourceTypeGeneral). Identifier" 

OR where there are versions:

Creator (PublicationYear): Title. Version. Publisher. (resourceTypeGeneral). Identifier

**Comment by timvdstap** [comment]
My bad, thanks for clarifying @Br-Johnson !

**Comment by Br-Johnson** [comment]
Mind you I just noticed that the order in which the publisher and resourceTypeGeneral are displayed in CKAN is backwards.

The order according to DataCite reccommendations should be:

 "Creator (PublicationYear): Title. **Publisher**. **(resourceTypeGeneral)**. Identifier

and currently it's

Creator (PublicationYear): Title. **(resourceTypeGeneral).** **Publisher.** Identifier

Lastly, identifying a publisher in the metadata intake form is not documented with tool tips and the publisher is not included in the preview.

**Comment by fostermh** [comment]
The javascript library we are using to generate the citation does not have a DataCite format option. what you are seeing by default is APA. https://apastyle.apa.org/style-grammar-guidelines/references/examples/data-set-references

**Comment by fostermh** [comment]
btw, you probably already know about this service but it was new to me. https://citation.crosscite.org/

**Comment by fostermh** [comment]
as far as ckan is concerned this issue appears to be solved. If that is not the case, please re-open the issue and provide more detail as to what is not working.
