### ISSUE TITLE
Owner role does not appear in all CKAN records

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/ckan#20]
Take for example the 2019 CTD data set: https://iys.hakai.org/dataset/ca-cioos_9bcf7978-77eb-47da-9f3b-2d2eaa7df589

Anna Vazhova is listed as the owner and the metadata custodian in the metadata intake form, but her owner status does not appear in the CKAN record.

Same issue exists for this dataset: https://iys.hakai.org/dataset/ca-cioos_fdba20a9-0e91-4e37-bf5f-086b08d56209

Brian is listed as an owner in the metadata intake form but it doesn't show up in CKAN.

**Comment by fostermh** [comment]
updating iys server to latest version ckan version seems to fix this issue. closing for now, please reopen this is not the case.
